### ISSUE TITLE
Pooled or individual analysis for multiple risk analysis points/shapes (e.g COMARE postcodes)

### ISSUE THREAD

**Issue by peterhambly** [smallAreaHealthStatisticsUnit/rapidInquiryFacility#129] opened 2019-01-25 11:07 UTC
Currently the RIF analyses there in N bands with all the sites as on. It is proposed to extend the RIF to support:

* Individual site analysis;
* Pooled analysis (1 or more groups of sites). Groups would be defined from a categorisation variable in the shapefile. Would require changes to:
  * Shapefile load screen and controller;
  * JSON study definition format;  
  * Study extract and result tables;
  * R risk analysis code.

**Comment by devilgate** [comment] 2019-03-11 15:58
Duplicate of #125.

**Closed by devilgate** 2019-03-11 15:58 UTC
